# pandas 是python中 用于处理表格数据的库

In [1]:
import numpy as np
import pandas as pd

## DataFrames

In [4]:
data = [
['Nissan','Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
['Hyundai','Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
['Lotus', 'Elise', 2010, 218, 4,'MANUAL', 'convertible', 54990],
['GMC', 'Acadia', 2017, 194, 4,'AUTOMATIC','4dr SUV',34450],
['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]
columns = [
'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
'Transmission Type', 'Vehicle_Style', 'MSRP']

In [5]:
df = pd.DataFrame(data,columns=columns)
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

# Series

In [17]:
df.Make

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: str

In [21]:
df['Make']

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: str

In [22]:
df[['Make']]

      Make
0   Nissan
1  Hyundai
2    Lotus
3      GMC
4   Nissan

In [6]:
df[['Make', 'Model','MSRP']]

      Make     Model   MSRP
0   Nissan    Stanza   2000
1  Hyundai    Sonata  27150
2    Lotus     Elise  54990
3      GMC    Acadia  34450
4   Nissan  Frontier  32340

In [9]:
df['id'] = [1,2,3,4,5]  #添加列

In [11]:
df['id']

0    1
1    2
2    3
3    4
4    5
Name: id, dtype: int64

In [10]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,1
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,2
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,3
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,4
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,5

In [12]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [13]:
df.loc[1]  # 位置索引，这是第一列的索引值

Make                   Hyundai
Model                   Sonata
Year                      2017
Engine HP                  NaN
Engine Cylinders             4
Transmission Type    AUTOMATIC
Vehicle_Style            Sedan
MSRP                     27150
id                           2
Name: 1, dtype: object

In [26]:
df.iloc[1]  # 位置索引，这是没有显示出来，默认索引值

Make                   Hyundai
Model                   Sonata
Year                      2017
Engine HP                  NaN
Engine Cylinders             4
Transmission Type    AUTOMATIC
Vehicle_Style            Sedan
MSRP                     27150
id                           2
Name: b, dtype: object

In [23]:
df.index = ['a','b','c','d','e']
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
a,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,1
b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,2
c,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,3
d,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,4
e,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,5

In [29]:
df.loc['b']

Make                   Hyundai
Model                   Sonata
Year                      2017
Engine HP                  NaN
Engine Cylinders             4
Transmission Type    AUTOMATIC
Vehicle_Style            Sedan
MSRP                     27150
id                           2
Name: b, dtype: object

In [25]:
df.loc[['a','b']] # 范围索引

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
a,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,1
b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,2

In [27]:
df.iloc[1] # 默认索引值，永远不变，不受第一列索引值内容的改变的影响

Make                   Hyundai
Model                   Sonata
Year                      2017
Engine HP                  NaN
Engine Cylinders             4
Transmission Type    AUTOMATIC
Vehicle_Style            Sedan
MSRP                     27150
id                           2
Name: b, dtype: object

In [16]:
df.Make

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: str

In [30]:
df.reset_index()  #充值索引列为默认数值，保留原索引列内容

,index,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
0,a,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,1
1,b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,2
2,c,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,3
3,d,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,4
4,e,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,5

In [31]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
a,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,1
b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,2
c,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,3
d,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,4
e,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,5

In [32]:
df.loc['a']

Make                 Nissan
Model                Stanza
Year                   1991
Engine HP             138.0
Engine Cylinders          4
Transmission Type    MANUAL
Vehicle_Style         sedan
MSRP                   2000
id                        1
Name: a, dtype: object

In [36]:
df.iloc[0]

Make                 Nissan
Model                Stanza
Year                   1991
Engine HP             138.0
Engine Cylinders          4
Transmission Type    MANUAL
Vehicle_Style         sedan
MSRP                   2000
id                        1
Name: a, dtype: object

In [41]:
df = df.reset_index(drop = True) # 删除字母索引的列

In [42]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,1
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,2
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,3
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,4
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,5

In [43]:
df.loc['a']

KeyError: 'a'

In [44]:
df.iloc[0]

Make                 Nissan
Model                Stanza
Year                   1991
Engine HP             138.0
Engine Cylinders          4
Transmission Type    MANUAL
Vehicle_Style         sedan
MSRP                   2000
id                        1
Name: 0, dtype: object

# element wise operations

In [45]:
df['Engine HP']/100   # 操作pandas中dataframe的序列

0    1.38
1     NaN
2    2.18
3    1.94
4    2.61
Name: Engine HP, dtype: float64

In [46]:
df['Year'] >= 2010   # 操作pandas中dataframe的序列

0    False
1     True
2     True
3     True
4     True
Name: Year, dtype: bool

# filtering

In [47]:
df[df['Year'] >= 2010]  # 找出大于等于2010的数据

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,2
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,3
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,4
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,5

# String operations

In [50]:
df['Vehicle_Style'].str.replace(' ','_').str.lower()

0          sedan
1          sedan
2    convertible
3        4dr_suv
4         pickup
Name: Vehicle_Style, dtype: str

In [51]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,1
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,2
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,3
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,4
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,5

In [52]:
df['Vehicle_Style'] = df['Vehicle_Style'].str.replace(' ','_').str.lower() 
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,1
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,sedan,27150,2
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,3
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr_suv,34450,4
4,Nissan,Frontier,2017,261.0,6,MANUAL,pickup,32340,5

# Summarizing operations

In [53]:
df.MSRP.mean()

np.float64(30186.0)

In [54]:
df.MSRP.describe()

count        5.000000
mean     30186.000000
std      18985.044904
min       2000.000000
25%      27150.000000
50%      32340.000000
75%      34450.000000
max      54990.000000
Name: MSRP, dtype: float64

In [56]:
df.describe().round(2)  # 描述中的数值，保留2位小数

          Year  Engine HP  Engine Cylinders      MSRP    id
count     5.00       4.00              5.00      5.00  5.00
mean   2010.40     202.75              4.40  30186.00  3.00
std      11.26      51.30              0.89  18985.04  1.58
min    1991.00     138.00              4.00   2000.00  1.00
25%    2010.00     180.00              4.00  27150.00  2.00
50%    2017.00     206.00              4.00  32340.00  3.00
75%    2017.00     228.75              4.00  34450.00  4.00
max    2017.00     261.00              6.00  54990.00  5.00

In [57]:
df.nunique()  # 唯一值数量

Make                 4
Model                5
Year                 3
Engine HP            4
Engine Cylinders     2
Transmission Type    2
Vehicle_Style        4
MSRP                 5
id                   5
dtype: int64

# Missing value

In [60]:
df.isnull().sum()  # 检查dataframe中，所有值中的NaN情况

Make                 0
Model                0
Year                 0
Engine HP            1
Engine Cylinders     0
Transmission Type    0
Vehicle_Style        0
MSRP                 0
id                   0
dtype: int64

# Grouping

In [62]:
'''
SELECT
transmission_type,AVG(MSRP)
FROM
cars
GROUP BY
transmission_type
'''

'\nSELECT\ntransmission_type,AVG(MSRP)\nFROM\ncars\nGROUP BY\ntransmission_type\n'

In [64]:
df.groupby('Transmission Type').MSRP.mean() # 也可以是max ，min，sum等分组函数

Transmission Type
AUTOMATIC    30800.000000
MANUAL       29776.666667
Name: MSRP, dtype: float64

# Getting the NumPy arrays

In [66]:
df.MSRP.mean()

np.float64(30186.0)

In [75]:
#df.MSRP.values
df['MSRP'].values    # 两者效果是一样的

array([ 2000, 27150, 54990, 34450, 32340])

In [68]:
df.to_dict(orient = 'records')  # 转换成字典形式

[{'Make': 'Nissan',
  'Model': 'Stanza',
  'Year': 1991,
  'Engine HP': 138.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'sedan',
  'MSRP': 2000,
  'id': 1},
 {'Make': 'Hyundai',
  'Model': 'Sonata',
  'Year': 2017,
  'Engine HP': nan,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': 'sedan',
  'MSRP': 27150,
  'id': 2},
 {'Make': 'Lotus',
  'Model': 'Elise',
  'Year': 2010,
  'Engine HP': 218.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'convertible',
  'MSRP': 54990,
  'id': 3},
 {'Make': 'GMC',
  'Model': 'Acadia',
  'Year': 2017,
  'Engine HP': 194.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': '4dr_suv',
  'MSRP': 34450,
  'id': 4},
 {'Make': 'Nissan',
  'Model': 'Frontier',
  'Year': 2017,
  'Engine HP': 261.0,
  'Engine Cylinders': 6,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'pickup',
  'MSRP': 32340,
  'id': 5}]